// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaBackend.Data;

#nullable disable

namespace SocialMediaBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260411171630_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("LikesQnt")
                        .HasColumnType("int");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            Bio = "Great introduction, looking forward to more posts!",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 4,
                            PostId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            Bio = "Nice reflections, John. Keep sharing!",
                            CreatedAt = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 2,
                            PostId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            Bio = "Welcome Maria! Glad to see your first post.",
                            CreatedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 5,
                            PostId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555555"),
                            Bio = "Thanks for the update, Alex!",
                            CreatedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 3,
                            PostId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("e6666666-6666-6666-6666-666666666666"),
                            Bio = "Nice post, Sofia! Looking forward to more.",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 6,
                            PostId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-7777-7777-777777777777"),
                            Bio = "Interesting ideas, Mike!",
                            CreatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 1,
                            PostId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("e8888888-8888-8888-8888-888888888888"),
                            Bio = "Nice story, Olga!",
                            CreatedAt = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 7,
                            PostId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesQnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SharesQnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Bio = "This is the very first post in the system.",
                            LikesQnt = 10,
                            SharesQnt = 2,
                            Title = "Welcome Post",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Bio = "Sharing some daily reflections.",
                            LikesQnt = 5,
                            SharesQnt = 1,
                            Title = "Daily Thoughts",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Bio = "Hello everyone, glad to join!",
                            LikesQnt = 7,
                            SharesQnt = 0,
                            Title = "Maria’s First Post",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Bio = "Quick update from Alex.",
                            LikesQnt = 3,
                            SharesQnt = 1,
                            Title = "Alex’s Update",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Bio = "Excited to share my first post.",
                            LikesQnt = 12,
                            SharesQnt = 4,
                            Title = "Sofia’s Post",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Bio = "Mike shares his ideas.",
                            LikesQnt = 8,
                            SharesQnt = 2,
                            Title = "Mike’s Thoughts",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Bio = "Olga writes about her day.",
                            LikesQnt = 15,
                            SharesQnt = 5,
                            Title = "Olga’s Story",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Bio = "Ivan shares his music journey.",
                            LikesQnt = 20,
                            SharesQnt = 7,
                            Title = "Ivan’s Rock",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Bio = "Important system update.",
                            LikesQnt = 30,
                            SharesQnt = 10,
                            Title = "Admin’s Announcement",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Bio = "Sharing my travel experience.",
                            LikesQnt = 18,
                            SharesQnt = 6,
                            Title = "John’s Travel",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Bio = "Cooking tips and tricks.",
                            LikesQnt = 25,
                            SharesQnt = 9,
                            Title = "Maria’s Recipe",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Bio = "Alex shares coding tips.",
                            LikesQnt = 14,
                            SharesQnt = 3,
                            Title = "Alex’s Coding",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Bio = "My latest painting.",
                            LikesQnt = 22,
                            SharesQnt = 8,
                            Title = "Sofia’s Art",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Bio = "Workout routines.",
                            LikesQnt = 16,
                            SharesQnt = 5,
                            Title = "Mike’s Fitness",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Bio = "Reviewing my favorite book.",
                            LikesQnt = 19,
                            SharesQnt = 7,
                            Title = "Olga’s Book Review",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Bio = "Football match highlights.",
                            LikesQnt = 28,
                            SharesQnt = 11,
                            Title = "Ivan’s Sports",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Bio = "System usage tips.",
                            LikesQnt = 12,
                            SharesQnt = 4,
                            Title = "Admin’s Tips",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Bio = "Sharing my playlist.",
                            LikesQnt = 21,
                            SharesQnt = 8,
                            Title = "John’s Music",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Bio = "Trip to the mountains.",
                            LikesQnt = 17,
                            SharesQnt = 6,
                            Title = "Maria’s Travel",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Bio = "Latest game review.",
                            LikesQnt = 24,
                            SharesQnt = 9,
                            Title = "Alex’s Gaming",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Bio = "Trip to the seaside.",
                            LikesQnt = 13,
                            SharesQnt = 4,
                            Title = "Sofia’s Travel",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Bio = "Learning C# step by step.",
                            LikesQnt = 9,
                            SharesQnt = 3,
                            Title = "Mike’s Coding Journey",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            Bio = "My favorite recipes.",
                            LikesQnt = 27,
                            SharesQnt = 12,
                            Title = "Olga’s Cooking",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("c6666666-6666-6666-6666-666666666666"),
                            Bio = "Exploring the forest trails.",
                            LikesQnt = 19,
                            SharesQnt = 6,
                            Title = "Ivan’s Hiking",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("c7777777-7777-7777-7777-777777777777"),
                            Bio = "How to keep your account safe.",
                            LikesQnt = 33,
                            SharesQnt = 14,
                            Title = "Admin’s Security Tips",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("c8888888-8888-8888-8888-888888888888"),
                            Bio = "Capturing the sunset.",
                            LikesQnt = 22,
                            SharesQnt = 7,
                            Title = "John’s Photography",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab"),
                            Email = "ADMIN@EXAMPLE.COM",
                            Login = "admin",
                            Nickname = "SuperAdmin",
                            PasswordHash = "FA7C65CB4BB64C06",
                            RegisteredAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("a3f2e1b4-9c5d-4f2a-8d7a-1b2c3d4e5f6a"),
                            Salt = "C1D2E3F4"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc"),
                            Email = "JOHN@EXAMPLE.COM",
                            Login = "john",
                            Nickname = "JohnDoe",
                            PasswordHash = "6D8208F48DDA7332",
                            RegisteredAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "D2E3F4A5"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd"),
                            Email = "MARIA@EXAMPLE.COM",
                            Login = "maria",
                            Nickname = "MariaSky",
                            PasswordHash = "96E8FCB521BCA47F",
                            RegisteredAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "E3F4A5B6"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de"),
                            Email = "ALEX@EXAMPLE.COM",
                            Login = "alex",
                            Nickname = "AlexStorm",
                            PasswordHash = "054D31AA38AEFAA2",
                            RegisteredAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "F4A5B6C7"
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-4cde-9f01-234567890abc"),
                            Email = "SOFIA@EXAMPLE.COM",
                            Login = "sofia",
                            Nickname = "SofiaLight",
                            PasswordHash = "9A6A64B2E3004012",
                            RegisteredAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "01234567"
                        },
                        new
                        {
                            Id = new Guid("12345678-9abc-4def-9012-345678901bcd"),
                            Email = "MIKE@EXAMPLE.COM",
                            Login = "mike",
                            Nickname = "MikeWave",
                            PasswordHash = "75C1721BEB275FCA",
                            RegisteredAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "12345678"
                        },
                        new
                        {
                            Id = new Guid("23456789-abcd-4ef0-9123-45678901cdef"),
                            Email = "OLGA@EXAMPLE.COM",
                            Login = "olga",
                            Nickname = "OlgaStar",
                            PasswordHash = "3C61FA60FC810A96",
                            RegisteredAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "23456789"
                        },
                        new
                        {
                            Id = new Guid("3456789a-bcde-4f01-9234-5678901def01"),
                            Email = "IVAN@EXAMPLE.COM",
                            Login = "ivan",
                            Nickname = "IvanRock",
                            PasswordHash = "16B2C8B41DFB08CF",
                            RegisteredAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "3456789A"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f2e1b4-9c5d-4f2a-8d7a-1b2c3d4e5f6a"),
                            Description = "Administrator role",
                            Title = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Description = "Regular user role",
                            Title = "User"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Comment", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaBackend.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
