// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaBackend.Data;

#nullable disable

namespace SocialMediaBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260430183644_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("LikesQnt")
                        .HasColumnType("int");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            Bio = "Great introduction, looking forward to more posts!",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 4,
                            PostId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            Bio = "Nice reflections, John. Keep sharing!",
                            CreatedAt = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 2,
                            PostId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            Bio = "Welcome Maria! Glad to see your first post.",
                            CreatedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 5,
                            PostId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555555"),
                            Bio = "Thanks for the update, Alex!",
                            CreatedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 3,
                            PostId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("e6666666-6666-6666-6666-666666666666"),
                            Bio = "Nice post, Sofia! Looking forward to more.",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 6,
                            PostId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-7777-7777-777777777777"),
                            Bio = "Interesting ideas, Mike!",
                            CreatedAt = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 1,
                            PostId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("e8888888-8888-8888-8888-888888888888"),
                            Bio = "Nice story, Olga!",
                            CreatedAt = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            LikesQnt = 7,
                            PostId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#3b82ff",
                            Emoji = "⚽",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "#8b5cf6",
                            Emoji = "📚",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "#ff3b3b",
                            Emoji = "🎬",
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Color = "#ff7a3b",
                            Emoji = "🎵",
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Color = "#22c55e",
                            Emoji = "🎮",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Color = "#06b6d4",
                            Emoji = "💻",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Color = "#facc15",
                            Emoji = "✈️",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Color = "#ef4444",
                            Emoji = "🏋️",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Color = "#f472b6",
                            Emoji = "🍥",
                            Name = "Anime"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Color = "#0ea5e9",
                            Emoji = "🧠",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Color = "#a855f7",
                            Emoji = "🎨",
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Color = "#14b8a6",
                            Emoji = "📸",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Color = "#6366f1",
                            Emoji = "🔬",
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Color = "#b45309",
                            Emoji = "🏺",
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Color = "#f97316",
                            Emoji = "🍳",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Color = "#16a34a",
                            Emoji = "🌿",
                            Name = "Nature"
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            Color = "#7c3aed",
                            Emoji = "🧠",
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            Color = "#64748b",
                            Emoji = "💼",
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            Color = "#dc2626",
                            Emoji = "🚗",
                            Name = "Cars"
                        },
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            Color = "#002f9dff",
                            Emoji = "🚀",
                            Name = "Space"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesQnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SharesQnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Bio = "This is the very first post in the system.",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 10,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SharesQnt = 2,
                            Title = "Welcome Post",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Bio = "Sharing some daily reflections.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 5,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SharesQnt = 1,
                            Title = "Daily Thoughts",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Bio = "Hello everyone, glad to join!",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 7,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SharesQnt = 0,
                            Title = "Maria’s First Post",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Bio = "Quick update from Alex.",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 3,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SharesQnt = 1,
                            Title = "Alex’s Update",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Bio = "Excited to share my first post.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 12,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SharesQnt = 4,
                            Title = "Sofia’s Post",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Bio = "Mike shares his ideas.",
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 8,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000006"),
                            SharesQnt = 2,
                            Title = "Mike’s Thoughts",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Bio = "Olga writes about her day.",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 15,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SharesQnt = 5,
                            Title = "Olga’s Story",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Bio = "Ivan shares his music journey.",
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 20,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000008"),
                            SharesQnt = 7,
                            Title = "Ivan’s Rock",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Bio = "Important system update.",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 30,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SharesQnt = 10,
                            Title = "Admin’s Announcement",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Bio = "Sharing my travel experience.",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 18,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SharesQnt = 6,
                            Title = "John’s Travel",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Bio = "Cooking tips and tricks.",
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 25,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SharesQnt = 9,
                            Title = "Maria’s Recipe",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Bio = "Alex shares coding tips.",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 14,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SharesQnt = 3,
                            Title = "Alex’s Coding",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Bio = "My latest painting.",
                            CreatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 22,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SharesQnt = 8,
                            Title = "Sofia’s Art",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Bio = "Workout routines.",
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 16,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SharesQnt = 5,
                            Title = "Mike’s Fitness",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Bio = "Reviewing my favorite book.",
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 19,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000008"),
                            SharesQnt = 7,
                            Title = "Olga’s Book Review",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Bio = "Football match highlights.",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 28,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SharesQnt = 11,
                            Title = "Ivan’s Sports",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Bio = "System usage tips.",
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 12,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SharesQnt = 4,
                            Title = "Admin’s Tips",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Bio = "Sharing my playlist.",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 21,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SharesQnt = 8,
                            Title = "John’s Music",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Bio = "Trip to the mountains.",
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 17,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SharesQnt = 6,
                            Title = "Maria’s Travel",
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd")
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Bio = "Latest game review.",
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 24,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SharesQnt = 9,
                            Title = "Alex’s Gaming",
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Bio = "Trip to the seaside.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 13,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000006"),
                            SharesQnt = 4,
                            Title = "Sofia’s Travel",
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc")
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Bio = "Learning C# step by step.",
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 9,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SharesQnt = 3,
                            Title = "Mike’s Coding Journey",
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd")
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            Bio = "My favorite recipes.",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 27,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000008"),
                            SharesQnt = 12,
                            Title = "Olga’s Cooking",
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef")
                        },
                        new
                        {
                            Id = new Guid("c6666666-6666-6666-6666-666666666666"),
                            Bio = "Exploring the forest trails.",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 19,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SharesQnt = 6,
                            Title = "Ivan’s Hiking",
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01")
                        },
                        new
                        {
                            Id = new Guid("c7777777-7777-7777-7777-777777777777"),
                            Bio = "How to keep your account safe.",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 33,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SharesQnt = 14,
                            Title = "Admin’s Security Tips",
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab")
                        },
                        new
                        {
                            Id = new Guid("c8888888-8888-8888-8888-888888888888"),
                            Bio = "Capturing the sunset.",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikesQnt = 22,
                            RaceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SharesQnt = 7,
                            Title = "John’s Photography",
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.PostInterest", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PostsInterests");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            PostId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            PostId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PostId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            PostId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            PostId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            PostId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            PostId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            PostId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            PostId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            PostId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PostId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            PostId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            PostId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("12121212-1212-1212-1212-121212121212")
                        },
                        new
                        {
                            PostId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("15151515-1515-1515-1515-151515151515")
                        },
                        new
                        {
                            PostId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("16161616-1616-1616-1616-161616161616")
                        },
                        new
                        {
                            PostId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            PostId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            PostId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            PostId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PostId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            PostId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            PostId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            PostId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            PostId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            PostId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            PostId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            PostId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            PostId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PostId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            PostId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            PostId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("16161616-1616-1616-1616-161616161616")
                        },
                        new
                        {
                            PostId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            PostId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("14141414-1414-1414-1414-141414141414")
                        },
                        new
                        {
                            PostId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            PostId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PostId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            PostId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            PostId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            PostId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            PostId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            PostId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            PostId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            PostId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            PostId = new Guid("c5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            PostId = new Guid("c5555555-5555-5555-5555-555555555555"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PostId = new Guid("c6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            PostId = new Guid("c6666666-6666-6666-6666-666666666666"),
                            InterestId = new Guid("12121212-1212-1212-1212-121212121212")
                        },
                        new
                        {
                            PostId = new Guid("c7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("13131313-1313-1313-1313-131313131313")
                        },
                        new
                        {
                            PostId = new Guid("c7777777-7777-7777-7777-777777777777"),
                            InterestId = new Guid("14141414-1414-1414-1414-141414141414")
                        },
                        new
                        {
                            PostId = new Guid("c8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            PostId = new Guid("c8888888-8888-8888-8888-888888888888"),
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Elf",
                            ThemeColorHex = "#3bff5e"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Dark Elf",
                            ThemeColorHex = "#7a3bff"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Dwarf",
                            ThemeColorHex = "#b87333"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Human",
                            ThemeColorHex = "#3b82ff"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Orc",
                            ThemeColorHex = "#4b5320"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Vampire",
                            ThemeColorHex = "#8b0000"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Werewolf",
                            ThemeColorHex = "#5c4033"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Goblin",
                            ThemeColorHex = "#7fff00"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Troll",
                            ThemeColorHex = "#556b2f"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragonborn",
                            ThemeColorHex = "#ff7a3b"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Name = "Angel",
                            ThemeColorHex = "#ffd700"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Name = "Demon",
                            ThemeColorHex = "#ff3b3b"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Name = "Undead",
                            ThemeColorHex = "#aaaaaa"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Name = "Fairy",
                            ThemeColorHex = "#ff69b4"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Name = "Elemental",
                            ThemeColorHex = "#3bfff2"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RaceId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab"),
                            Email = "ADMIN@EXAMPLE.COM",
                            Login = "admin",
                            Nickname = "SuperAdmin",
                            PasswordHash = "FA7C65CB4BB64C06",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RegisteredAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("a3f2e1b4-9c5d-4f2a-8d7a-1b2c3d4e5f6a"),
                            Salt = "C1D2E3F4"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc"),
                            Email = "JOHN@EXAMPLE.COM",
                            Login = "john",
                            Nickname = "JohnDoe",
                            PasswordHash = "6D8208F48DDA7332",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000002"),
                            RegisteredAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "D2E3F4A5"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd"),
                            Email = "MARIA@EXAMPLE.COM",
                            Login = "maria",
                            Nickname = "MariaSky",
                            PasswordHash = "96E8FCB521BCA47F",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000003"),
                            RegisteredAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "E3F4A5B6"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de"),
                            Email = "ALEX@EXAMPLE.COM",
                            Login = "alex",
                            Nickname = "AlexStorm",
                            PasswordHash = "054D31AA38AEFAA2",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000004"),
                            RegisteredAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "F4A5B6C7"
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-4cde-9f01-234567890abc"),
                            Email = "SOFIA@EXAMPLE.COM",
                            Login = "sofia",
                            Nickname = "SofiaLight",
                            PasswordHash = "9A6A64B2E3004012",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000005"),
                            RegisteredAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "01234567"
                        },
                        new
                        {
                            Id = new Guid("12345678-9abc-4def-9012-345678901bcd"),
                            Email = "MIKE@EXAMPLE.COM",
                            Login = "mike",
                            Nickname = "MikeWave",
                            PasswordHash = "75C1721BEB275FCA",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000006"),
                            RegisteredAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "12345678"
                        },
                        new
                        {
                            Id = new Guid("23456789-abcd-4ef0-9123-45678901cdef"),
                            Email = "OLGA@EXAMPLE.COM",
                            Login = "olga",
                            Nickname = "OlgaStar",
                            PasswordHash = "3C61FA60FC810A96",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000007"),
                            RegisteredAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "23456789"
                        },
                        new
                        {
                            Id = new Guid("3456789a-bcde-4f01-9234-5678901def01"),
                            Email = "IVAN@EXAMPLE.COM",
                            Login = "ivan",
                            Nickname = "IvanRock",
                            PasswordHash = "16B2C8B41DFB08CF",
                            RaceId = new Guid("10000000-0000-0000-0000-000000000008"),
                            RegisteredAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Salt = "3456789A"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UsersInterests");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab"),
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            UserId = new Guid("c1d2e3f4-5678-4abc-9def-1234567890ab"),
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc"),
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            UserId = new Guid("d2e3f4a5-6789-4bcd-8efa-2345678901bc"),
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd"),
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            UserId = new Guid("e3f4a5b6-7890-4cde-9fab-3456789012cd"),
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de"),
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            UserId = new Guid("f4a5b6c7-8901-4def-9abc-4567890123de"),
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc"),
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            UserId = new Guid("01234567-89ab-4cde-9f01-234567890abc"),
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd"),
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            UserId = new Guid("12345678-9abc-4def-9012-345678901bcd"),
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef"),
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            UserId = new Guid("23456789-abcd-4ef0-9123-45678901cdef"),
                            InterestId = new Guid("12121212-1212-1212-1212-121212121212")
                        },
                        new
                        {
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01"),
                            InterestId = new Guid("15151515-1515-1515-1515-151515151515")
                        },
                        new
                        {
                            UserId = new Guid("3456789a-bcde-4f01-9234-5678901def01"),
                            InterestId = new Guid("16161616-1616-1616-1616-161616161616")
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f2e1b4-9c5d-4f2a-8d7a-1b2c3d4e5f6a"),
                            Description = "Administrator role",
                            Title = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-8f9a-4b1c-9d2e-3f4a5b6c7d8e"),
                            Description = "Regular user role",
                            Title = "User"
                        });
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Comment", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaBackend.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.HasOne("SocialMediaBackend.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.PostInterest", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Interest", "Interest")
                        .WithMany("PostsInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaBackend.Data.Entities.Post", "Post")
                        .WithMany("PostsInterests")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.HasOne("SocialMediaBackend.Data.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Race");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.UserInterest", b =>
                {
                    b.HasOne("SocialMediaBackend.Data.Entities.Interest", "Interest")
                        .WithMany("UsersInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaBackend.Data.Entities.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Interest", b =>
                {
                    b.Navigation("PostsInterests");

                    b.Navigation("UsersInterests");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostsInterests");
                });

            modelBuilder.Entity("SocialMediaBackend.Data.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
